import type { Reminder, PassDesign } from "../types";
import { PRIORITY_COLORS } from "../types";

function rgb(hex: string): string {
  const n = parseInt(hex.slice(1), 16);
  return `rgb(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255})`;
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
  });
}

function fmtTime(iso: string): string {
  return new Date(iso).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
}

export interface PassContent {
  description: string;
  organizationName: string;
  backgroundColor: string;
  foregroundColor: string;
  labelColor: string;
  eventTicket: {
    headerFields: object[];
    primaryFields: object[];
    secondaryFields: object[];
    auxiliaryFields: object[];
    backFields: object[];
  };
  relevantDate: string;
  expirationDate?: string;
  voided?: boolean;
}

/**
 * Build the pass.json field layout for each of the three designs.
 * All use the eventTicket style; they differ in color scheme and
 * information density.
 */
export function buildPassContent(reminder: Reminder, design: PassDesign): PassContent {
  const priorityColor = PRIORITY_COLORS[reminder.priority];
  const base = {
    description: `${reminder.name} — ${reminder.course}`,
    organizationName: "Quiz Reminder",
    relevantDate: reminder.dueDate,
    expirationDate: reminder.completed ? new Date().toISOString() : undefined,
    voided: reminder.completed || undefined,
  };

  if (design === "airline") {
    // Design 1 — Airline Ticket: blue gradient feel, dense structured grid
    return {
      ...base,
      backgroundColor: rgb("#1d4ed8"),
      foregroundColor: rgb("#ffffff"),
      labelColor: rgb("#bfdbfe"),
      eventTicket: {
        headerFields: [
          { key: "course", label: "COURSE", value: reminder.course },
        ],
        primaryFields: [
          { key: "name", label: reminder.type.toUpperCase(), value: reminder.name },
        ],
        secondaryFields: [
          { key: "date", label: "DATE", value: fmtDate(reminder.dueDate) },
          { key: "time", label: "BOARDING", value: fmtTime(reminder.dueDate) },
          { key: "gate", label: "GATE", value: reminder.location || "TBD" },
        ],
        auxiliaryFields: [
          { key: "seat", label: "SEAT", value: reminder.course.slice(0, 3).toUpperCase() },
          { key: "priority", label: "CLASS", value: reminder.priority.toUpperCase() },
          { key: "status", label: "STATUS", value: reminder.completed ? "DONE" : "ON TIME" },
        ],
        backFields: backFields(reminder),
      },
    };
  }

  if (design === "colorful") {
    // Design 2 — Colorful Stack: playful, priority color drives the card
    return {
      ...base,
      backgroundColor: rgb(priorityColor),
      foregroundColor: rgb("#ffffff"),
      labelColor: rgb("#ffffff"),
      eventTicket: {
        headerFields: [
          { key: "countdown", label: "DUE", value: fmtDate(reminder.dueDate) },
        ],
        primaryFields: [
          { key: "name", label: reminder.course, value: reminder.name },
        ],
        secondaryFields: [
          { key: "time", label: "⏰ TIME", value: fmtTime(reminder.dueDate) },
          { key: "type", label: "✏️ TYPE", value: reminder.type },
        ],
        auxiliaryFields: [
          { key: "priority", label: "🔥 PRIORITY", value: reminder.priority },
        ],
        backFields: backFields(reminder),
      },
    };
  }

  // Design 4 — Event Ticket (default): dark premium, accent info cards
  return {
    ...base,
    backgroundColor: rgb("#18181b"),
    foregroundColor: rgb("#fafafa"),
    labelColor: rgb(priorityColor),
    eventTicket: {
      headerFields: [
        { key: "priority", label: "PRIORITY", value: reminder.priority.toUpperCase() },
      ],
      primaryFields: [
        { key: "name", label: reminder.course, value: reminder.name },
      ],
      secondaryFields: [
        { key: "date", label: "DUE DATE", value: fmtDate(reminder.dueDate) },
        { key: "time", label: "TIME", value: fmtTime(reminder.dueDate) },
      ],
      auxiliaryFields: [
        { key: "type", label: "TYPE", value: reminder.type },
        ...(reminder.location
          ? [{ key: "location", label: "LOCATION", value: reminder.location }]
          : []),
      ],
      backFields: backFields(reminder),
    },
  };
}

function backFields(reminder: Reminder): object[] {
  return [
    { key: "notes", label: "Notes", value: reminder.notes || "—" },
    { key: "created", label: "Created", value: fmtDate(reminder.createdAt) },
    {
      key: "about",
      label: "About",
      value: "Generated by Quiz Reminder. This pass updates when the reminder changes and expires when completed.",
    },
  ];
}
